const products = [
    {
      id: 0,
      name: "Iphone 11",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "iphone",
      price: 2999.99,
      image: "./img/iphone-11.jpg",
      sale: true,
      saleAmount: 200,
    },
    {
      id: 1,
      name: "Iphone 13",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "iphone",
      price: 5200.5,
      image: "./img/iphone-13.jpg",
    },
    {
      id: 2,
      name: "Iphone 12",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "iphone",
      price: 4444.44,
      image: "./img/Iphone-12.jpg",
      sale: true,
      saleAmount: 451,
    },
    {
      id: 3,
      name: "huawei p50 pro",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "huawei",
      price: 1330,
      image: "./img/huawei-2.jpg",
    },
    {
      id: 4,
      name: "huawei p20 lite",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "huawei",
      price: 2250,
      image: "./img/huawei-1.jpg",
    },
    {
      id: 5,
      name: "Nokia c300",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "nokia",
      price: 950,
      image: "./img/Nokia.jpg",
      sale: true,
      saleAmount: 250,
    },
    {
      id: 6,
      name: "Nokia n70",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "nokia",
      price: 690,
      image: "./img/Nokia-2.jpg",
    },
    {
      id: 7,
      name: "Samsung a53",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "samsung",
      price: 1440,
      image: "./img/Samsung-a53.jpg",
    },
    {
      id: 8,
      name: "Samsung s20",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "samsung",
      price: 2620.2,
      image: "./img/Samsung-s20.jpg",
      sale: true,
      saleAmount: 300,
    },
    {
      id: 9,
      name: "Samsung s22",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "samsung",
      price: 3399.99,
      image: "./img/Samsung-s22.jpg",
    },
  ];